# Generated by Django 5.1.4 on 2024-12-17 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='api.agent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AgentPromptBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_type', models.CharField(choices=[('true', 'True Branch'), ('false', 'False Branch')], max_length=5)),
                ('order', models.IntegerField()),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='api.agentcondition')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prompt')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
